---
title: "Week_7_Assignment_05_Guruprasad_VelikaduKrishnamoorthy"
author: "Guruprasad Velikadu Krishnamoorthy"
date: "2023-01-29"
output: 
  pdf_document: 
    highlight: espresso
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/Gurup/GURU/Learning/Masters/Term_2/DSC520_T302_Statistics_for_Data_Science/Week_1/forked_example/dsc520_Week_1_Assignment_forkedExample")
```

```{r}
# Load the `data/r4ds/heights.csv` to
heights_df <- read.csv("data/r4ds/heights.csv")
```
```{r}
# Using `cor()` compute correlation coefficients for
# height vs. earn
cor(heights_df$height,heights_df$earn)
# age vs. earn
cor(heights_df$age,heights_df$earn)
# ed vs. earn
cor(heights_df$ed,heights_df$earn)
```

```{r}
# Spurious correlation
# The following is data on US spending on science, space, and technology in millions of today's dollars
# and Suicides by hanging strangulation and suffocation for the years 1999 to 2009
# Compute the correlation between these variables
tech_spending <- c(18079, 18594, 19753, 20734, 20831, 23029, 23597, 23584, 25525, 27731, 29449)
suicides <- c(5427, 5688, 6198, 6462, 6635, 7336, 7248, 7491, 8161, 8578, 9000)
cor(tech_spending,suicides)

```




